// flow-typed signature: 91cb75a216a7b0e5cd45b87547fcd6ee
// flow-typed version: <<STUB>>/modern-normalize_v^1.1.0/flow_v0.162.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modern-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modern-normalize' {
  declare module.exports: any;
}
